### ISSUE TITLE
Search results is empty, although the result count is there (result.total > 10)

### ISSUE THREAD

**Issue by mesakarghm** [RediSearch/RediSearch#2550]
The issue is very weird and I have no idea on how to replicate the problem. 

Here's my RediSearch Schema: 
                TextField("media_id", sortable=True), NumericField("n_sig"), TextField("signature"),
                NumericField("created_at",sortable=True), TextField("bucket_1"), TextField("bucket_2"),
                TextField("bucket_3")..........TextField("bucket_25")
Just a heads up, I am designing an audio search system, where the audio is converted into multiple 6 length hashes which I am storing in 25 different buckets. 

A sample query on my end is: 
@bucket_0:3581177 | 325905 | 1829934 | 223442 | 3104621 @bucket_2:5020915 | 3427151 | 3951315 | 5778399 | 4589712 | 3413601 @bucket_4:133896 | 145672 | 3815688 @bucket_5:4332792 | 1031738 | 4177807 | 3731096 | 4181445 | 3473978 @bucket_17:2543887 | 2941138 | 2482386 | 1295230 | 1482179 | 1875358 | 3147066 | 607576 | 3697420 | 5740835 | 4843790 | 182646 | 3495725 | 3495686 | 5720109 | 5723917 | 182678 | 182646 | 1823567 | 293080 | 5834351 | 371729 | 2639144 | 5448747 | 3806575 | 3741036 | 2221955 | 29297 | 4806467 | 3473470 | 1823618 | 1364815 | 1369986 | 1828745 | 1295293 | 3085312 | 1366062 | 1369956 | 1366066 | 2218114 | 4134094@bucket_18:3715066 | 336483 | 1716323 | 4245082 | 3259030 | 3271574 | 3347981 | 5310688 | 323719 | 2426669 | 4415424 | 4231104 | 4243604 | 608207 | 5013994 | 3452402 | 2554355 | 376949 | 2314984 | 757829 | 4963789 | 1547829 | 3827654 | 5149155 | 4218772 | 4229801 | 2206356 | 2211988 | 4095461 | 127072 | 3795629 | 340128 | 432057 | 5157605 | 1020491 | 3808396 | 1260052 | 3035425 | 3705758 | 1181003 | 966087@bucket_19:4248450 | 4930185 | 5493653 | 777949 | 5497019 | 4159962 | 3360210 @bucket_21:2976463 | 2980047 | 1525232 @bucket_22:335804 | 1638428 | 2520488 | 169068 | 169068 | 855043 | 855112 | 3750022 | 1678313 | 3296916 | 4816424 | 4836110 | 1506043 | 1545872 | 3735194 | 2467082 | 4987402 | 5098255 | 794739 | 794727 | 4007201 @bucket_23:2852236 | 5320226 | 3561263 | 1710031 | 1513408 @bucket_24:611020 | 2371505 | 2358239 | 1151382 | 932858 | 2955396 | 3537796 

(The query size has been reduced for readability. I'll attach a full query below.)

Currently, I have 16k audios indexed in my system, with 5 gigs of memory usage. While the system is working fine with audio search where audio length is less than 10. When the audio length increases (consequently increasing the query length), redisearch does not give any result although it shows many documents are getting matched. 

"""
[2022-02-05 13:57:51,882][9781][ERROR] - RediSearchHelper: Error searching record float() argument must be a string or a number, not 'list'
[2022-02-05 13:57:51,885][9781][ERROR] - Traceback (most recent call last):
  File "/home/sakar/IdenTV/Vader/vader-sound-around/audio_utils/RediSearchHelper.py", line 49, in search_record
    res = self.redisearch_client.search(query)
  File "/home/sakar/.local/share/virtualenvs/vader-sound-around-Q8dlzyZc/lib/python3.7/site-packages/redisearch/client.py", line 481, in search
    with_scores=query._with_scores)
  File "/home/sakar/.local/share/virtualenvs/vader-sound-around-Q8dlzyZc/lib/python3.7/site-packages/redisearch/result.py", line 35, in __init__
    score = float(res[i+1]) if with_scores else None
TypeError: float() argument must be a string or a number, not 'list'

[2022-02-05 13:57:51,885][9781][DEBUG] - Searching Redis took 2.243024306000052 seconds
[2022-02-05 13:57:51,885][9781][ERROR] - 'NoneType' object has no attribute 'total'
[2022-02-05 13:57:51,887][9781][ERROR] - Traceback (most recent call last):
  File "audio_search/audio_search.py", line 54, in search
    if res.total:
AttributeError: 'NoneType' object has no attribute 'total'
"""
![Screenshot from 2022-02-05 14-12-42](https://user-images.githubusercontent.com/39232725/152634539-da17af7c-61df-429d-b5ad-cca8d7fdc1de.png)

Redisearch Version : 2.2.7 
How to replicate: No Idea (ran the same redisearch locally using docker, and the problem did not occur there. I'm guessing it has something to do with the number of indexed document that I had. I had 16k where the problem occurred, and only 132 locally). 

Full query: 

[sample_query.txt](https://github.com/RediSearch/RediSearch/files/8007658/sample_query.txt)

**Comment by ashtul** [comment]
@mesakarghm 
This can be a timeout issue. You can try adding to the query `TIMEOUT (xxx ms)` and see if you get the results.
