### ISSUE TITLE
Could not load the Index and search JSON documents

### ISSUE THREAD

**Issue by rameshsubramanian82** [RediSearch/RediSearch#3107]
We are trying to use the Search functionality of Redis Cache using RediSearch. However, the downloaded Redis API versions does not have the module which supports Search functionality. When we try to query the document, we are getting the below error.

redis.clients.jedis.exceptions.JedisDataException: ERR unknown command 'FT.SEARCH'
	at redis.clients.jedis.Protocol.processError(Protocol.java:135) ~[jedis-3.6.0.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:169) ~[jedis-3.6.0.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:223) ~[jedis-3.6.0.jar:na]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352) ~[jedis-3.6.0.jar:na]
	at redis.clients.jedis.Connection.getUnflushedObjectMultiBulkReply(Connection.java:314) ~[jedis-3.6.0.jar:na]
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:319) ~[jedis-3.6.0.jar:na]
	at io.redisearch.client.Client.search(Client.java:383) ~[jredisearch-2.0.0.jar:na]
	at io.redisearch.client.Client.search(Client.java:363) ~[jredisearch-2.0.0.jar:na]
	at 

Here is the codebase which we are trying to execute.

public Map<String,Object> search(String queryString, int offset, int limit, String sortBy, boolean ascending ) {
        Map<String,Object> returnValue = new HashMap<>();
        Map<String,Object> resultMeta = new HashMap<>();

        // Create a simple query
        Query query = new Query("10059_62276899_62275100")
                .setWithScores()
                .limit(offset, limit);

        // Execute the query
        SearchResult queryResult = rediSearchClient.search(query);

        // Adding the query string for information purpose
        resultMeta.put("queryString",queryString);

        // Get the total number of documents and other information for this query:
        resultMeta.put("totalResults", queryResult.totalResults);
        resultMeta.put("offset", offset);
        resultMeta.put("limit", limit);

        returnValue.put("meta", resultMeta);

        // the docs are returned as an array of document, with the document itself being a list of k/v json documents
        // not the easiest to manipulate
        // the `raw_docs` is used to view the structure
        // the `docs` will contain the list of document that is more developer friendly
        //      capture in  https://github.com/RediSearch/JRediSearch/issues/121
        returnValue.put("raw_docs", queryResult.docs);

        // remove the properties array and create attributes
        List<Map<String, Object>> docsToReturn = new ArrayList<>();
        List<Document> docs =  queryResult.docs;

        for (Document doc :docs) {

            Map<String,Object> props = new HashMap<>();
            Map<String,Object> meta = new HashMap<>();
            meta.put("id", doc.getId());
            meta.put("score", doc.getScore());
            doc.getProperties().forEach( e -> {
                props.put( e.getKey(), e.getValue() );
            });

            Map<String,Object> docMeta = new HashMap<>();
            docMeta.put("meta",meta);
            docMeta.put("fields",props);
            docsToReturn.add(docMeta);
        }

        returnValue.put("docs", docsToReturn);

        return returnValue;
    }

Can you please help me understand how I can load the Search Module which is not available in the Redis Search API which I could download from this redis.io site.

**Comment by gkorland** [comment]
You need to have the RediSearch module loaded. The easiest way to do it is to run Redis-Stack see: https://redis.io/download/#redis-stack-downloads
