### ISSUE TITLE
unable to build main in docker

### ISSUE THREAD

**Issue by LennertDefauw1** [RediSearch/RediSearch#3341]
Using following dockerfile

```
FROM ubuntu:20.04

ENV NODEJS_VERSION=16

RUN set -ex \
 && apt-get update -y && apt-get upgrade -y \
 && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y nginx curl musl-tools nano iputils-ping procps iproute2 imagemagick software-properties-common build-essential llvm cmake libclang1 libclang-dev cargo git wget redis

RUN git clone --recursive "https://github.com/RediSearch/RediSearch.git" /redis-search \
 && cd /redis-search \
 && make setup

```

with command

```shell
docker build -t testing .
```

results in

```
NO_PY2=1 /redis-search/deps/readies/bin/getpudb
running install
/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'test_requires'
  warnings.warn(msg)
/usr/local/lib/python3.8/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    setup(
  File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/dist-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.8/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.ensure_finalized()  # finalize before bdist_egg munges install cmd
  File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/local/lib/python3.8/dist-packages/setuptools/command/easy_install.py", line 311, in finalize_options
    self.local_index = Environment(self.shadow_path + sys.path)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 1044, in __init__
    self.scan(search_path)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 1077, in scan
    self.add(dist)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 1096, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2631, in hashcmp
    self.parsed_version,
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2678, in parsed_version
    self._parsed_version = parse_version(self.version)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '0.23ubuntu1'

In /redis-search/deps/readies/bin/getpudb:
29                                      xinstall python3-dev
30                              fi
31                              # --prefix= is required for install to succeed
32   >>>                        runn python3 setup.py install --user --prefix=
33                              cd /tmp
34                              $OP rm -rf $tmpdir
35                              PY3=1

command failed: NO_PY2=1 /redis-search/deps/readies/bin/getpudb
make: *** [Makefile:430: setup] Error 1
```

This breaks CICD of my project

**Comment by LennertDefauw1** [comment]
is it related to this commit? https://github.com/RedisLabsModules/readies/commit/aa7a71dc1835800504c51d227bad2dea4c2f9d90

**Comment by LennertDefauw1** [comment]
no update on this? still happening
