### ISSUE TITLE
[Redis 7.2.1 crashed by signal: 4, si_code: 2]

### ISSUE THREAD

**Issue by jackchentzh** [RediSearch/RediSearch#4097]
**Describe the bug**
using the redis-py example: Vector Similarity, https://redis-py.readthedocs.io/en/stable/examples/search_vector_similarity_examples.html
After the vector index be created, when i restart the server, it will occur error: (logfile)  oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
884185:C 18 Nov 2023 16:22:12.392 * Redis version=7.2.1, bits=64, commit=00000000, modified=0, pid=884185, just started
884185:C 18 Nov 2023 16:22:12.392 * Configuration loaded
884185:M 18 Nov 2023 16:22:12.393 * monotonic clock: POSIX clock_gettime
884185:M 18 Nov 2023 16:22:12.393 * Running mode=standalone, port=6394.
884185:M 18 Nov 2023 16:22:12.395 * <search> Redis version found by RedisSearch : 7.2.1 - oss
884185:M 18 Nov 2023 16:22:12.395 * <search> RediSearch version 2.6.5 (Git=HEAD-71bd22f3)
884185:M 18 Nov 2023 16:22:12.395 * <search> Low level api version 1 initialized successfully
884185:M 18 Nov 2023 16:22:12.395 * <search> concurrent writes: OFF, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  1000000, search pool size: 20, index pool size: 8,
884185:M 18 Nov 2023 16:22:12.395 * <search> Initialized thread pool!
884185:M 18 Nov 2023 16:22:12.395 * <search> Enabled role change notification
884185:M 18 Nov 2023 16:22:12.395 * Module 'search' loaded from /opt/redis-work/lib/redisearch.so
884185:M 18 Nov 2023 16:22:12.396 * <timeseries> RedisTimeSeries version 10805, git_sha=a7a296c8f3f6e312811032233a468d57d45957ca
884185:M 18 Nov 2023 16:22:12.396 * <timeseries> Redis version found by RedisTimeSeries : 7.2.1 - oss
884185:M 18 Nov 2023 16:22:12.396 * <timeseries> loaded default CHUNK_SIZE_BYTES policy: 4096
884185:M 18 Nov 2023 16:22:12.396 * <timeseries> loaded server DUPLICATE_POLICY: block
884185:M 18 Nov 2023 16:22:12.396 * <timeseries> Setting default series ENCODING to: compressed
884185:M 18 Nov 2023 16:22:12.396 * <timeseries> Detected redis oss
884185:M 18 Nov 2023 16:22:12.396 * Module 'timeseries' loaded from /opt/redis-work/lib/redistimeseries.so
884185:M 18 Nov 2023 16:22:12.397 * <ReJSON> version: 20405 git sha: 4e80773 branch: HEAD
884185:M 18 Nov 2023 16:22:12.397 * <ReJSON> Exported RedisJSON_V1 API
884185:M 18 Nov 2023 16:22:12.397 * <ReJSON> Exported RedisJSON_V2 API
884185:M 18 Nov 2023 16:22:12.397 * <ReJSON> Exported RedisJSON_V3 API
884185:M 18 Nov 2023 16:22:12.397 * <ReJSON> Enabled diskless replication
884185:M 18 Nov 2023 16:22:12.397 * <ReJSON> Created new data type 'ReJSON-RL'
884185:M 18 Nov 2023 16:22:12.397 * Module 'ReJSON' loaded from /opt/redis-work/lib/rejson.so
884185:M 18 Nov 2023 16:22:12.397 * <search> Acquired RedisJSON_V3 API
884185:M 18 Nov 2023 16:22:12.397 * <bf> RedisBloom version 2.4.4 (Git=unknown)
884185:M 18 Nov 2023 16:22:12.397 * Module 'bf' loaded from /opt/redis-work/lib/redisbloom.so
884185:M 18 Nov 2023 16:22:12.400 * Server initialized
884185:M 18 Nov 2023 16:22:12.400 * <search> Loading event starts
884185:M 18 Nov 2023 16:22:12.400 * Reading RDB base file on AOF loading...
884185:M 18 Nov 2023 16:22:12.400 * Loading RDB produced by version 7.2.1
884185:M 18 Nov 2023 16:22:12.400 * RDB age 330 seconds
884185:M 18 Nov 2023 16:22:12.400 * RDB memory usage when created 0.61 Mb
884185:M 18 Nov 2023 16:22:12.400 * RDB is base AOF
884185:M 18 Nov 2023 16:22:12.400 * Done loading RDB, keys loaded: 0, keys expired: 0.
884185:M 18 Nov 2023 16:22:12.400 * DB loaded from base file test-94.aof.1.base.rdb: 0.000 seconds
884185:M 18 Nov 2023 16:22:12.401 # <search> creating vector index. Server memory limit: 838860800B, required memory: 147568B, available memory: 838203928B
884185:M 18 Nov 2023 16:22:12.401 # == CRITICAL == This server is sending an error to its AOF-loading-client: '-NOPERM ACLs rules changed between the moment the transaction was accumulated and the EXEC call. This command is no longer allowed for the following reason: no permission to execute the command or subcommand' after processing the command 'exec'
884185:M 18 Nov 2023 16:22:12.401 # == CRITICAL == This server is sending an error to its AOF-loading-client: '-NOPERM ACLs rules changed between the moment the transaction was accumulated and the EXEC call. This command is no longer allowed for the following reason: no permission to execute the command or subcommand' after processing the command 'exec'
884185:M 18 Nov 2023 16:22:12.401 # == CRITICAL == This server is sending an error to its AOF-loading-client: '-NOPERM ACLs rules changed between the moment the transaction was accumulated and the EXEC call. This command is no longer allowed for the following reason: no permission to execute the command or subcommand' after processing the command 'exec'
884185:M 18 Nov 2023 16:22:12.401 * DB loaded from incr file test-94.aof.1.incr.aof: 0.001 seconds
884185:M 18 Nov 2023 16:22:12.401 # <search> Skip background reindex scan, redis version contains loaded event.
884185:M 18 Nov 2023 16:22:12.401 * <search> Loading event ends
884185:M 18 Nov 2023 16:22:12.401 * DB loaded from append only file: 0.001 seconds
884185:M 18 Nov 2023 16:22:12.401 * Opening AOF incr file test-94.aof.1.incr.aof on server start
884185:M 18 Nov 2023 16:22:12.401 * Ready to accept connections tls.
if search, the server will crash. log file contents: 
884185:M 18 Nov 2023 17:16:37.617 # <search> creating vector index. Server memory limit: 838860800B, required memory: 147568B, available memory: 838072304B
.....

------ CLIENT LIST OUTPUT ------
id=122 addr=223.73.119.174:7659 laddr=192.168.0.5:6394 fd=14 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=345 qbuf-free=20129 argv-mem=229 multi-mem=0 rbs=1024 rbp=48 obl=0 oll=0 omem=0 tot-mem=22773 events=r cmd=FT.SEARCH user=super redir=-1 resp=2 lib-name=redis-py lib-ver=5.0.1

------ CURRENT CLIENT INFO ------
id=122 addr=223.73.119.174:7659 laddr=192.168.0.5:6394 fd=14 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=345 qbuf-free=20129 argv-mem=229 multi-mem=0 rbs=1024 rbp=48 obl=0 oll=0 omem=0 tot-mem=22773 events=r cmd=FT.SEARCH user=super redir=-1 resp=2 lib-name=redis-py lib-ver=5.0.1
argc: '18'
argv[0]: '"FT.SEARCH"'
argv[1]: '"index"'
argv[2]: '"@tag: {foo}=>[KNN 2 @vector $vec as score]"'
argv[3]: '"RETURN"'
argv[4]: '"4"'
argv[5]: '"id"'
argv[6]: '"num"'
argv[7]: '"tag"'
argv[8]: '"score"'
argv[9]: '"DIALECT"'
argv[10]: '"2"'
argv[11]: '"LIMIT"'
argv[12]: '"0"'
argv[13]: '"2"'
argv[14]: '"params"'
argv[15]: '"2"'
argv[16]: '"vec"'
argv[17]: '"\xdf\xb3\xbf>\x91\xebO?S\xa7\xd4>\x86q\x1f?\xa6lc>i\x03\x87>\xf4\x86\xcc> ZO?\xaa\xa7_?\x01W\x80>\x91\x9a\xc1>6\x91\xb7>\xf5;\xc1>\\\x8eB>\xf3\x03\xea=\xad\xcd\x18?O!z?e\x02\xee=86\x95>X\xc1H=\xf0\xa5\x10?\xebsw?\xfe\xa8W?\x03\x8a\x1b?\xd9\xf6p?\xb1\x19\x9e=\xb3$v>\x14E'?\x06fi?\x98\x89\xe1>\xcev\x18>g\xcc\xa0>"'

------ EXECUTING CLIENT INFO ------
id=122 addr=223.73.119.174:7659 laddr=192.168.0.5:6394 fd=14 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=345 qbuf-free=20129 argv-mem=229 multi-mem=0 rbs=1024 rbp=48 obl=0 oll=0 omem=0 tot-mem=22773 events=r cmd=FT.SEARCH user=super redir=-1 resp=2 lib-name=redis-py lib-ver=5.0.1
argc: '18'
argv[0]: '"FT.SEARCH"'
argv[1]: '"index"'
argv[2]: '"@tag: {foo}=>[KNN 2 @vector $vec as score]"'
argv[3]: '"RETURN"'
argv[4]: '"4"'
argv[5]: '"id"'
argv[6]: '"num"'
argv[7]: '"tag"'
argv[8]: '"score"'
argv[9]: '"DIALECT"'
argv[10]: '"2"'
argv[11]: '"LIMIT"'
argv[12]: '"0"'
argv[13]: '"2"'
argv[14]: '"params"'
argv[15]: '"2"'
argv[16]: '"vec"'
argv[17]: '"\xdf\xb3\xbf>\x91\xebO?S\xa7\xd4>\x86q\x1f?\xa6lc>i\x03\x87>\xf4\x86\xcc> ZO?\xaa\xa7_?\x01W\x80>\x91\x9a\xc1>6\x91\xb7>\xf5;\xc1>\\\x8eB>\xf3\x03\xea=\xad\xcd\x18?O!z?e\x02\xee=86\x95>X\xc1H=\xf0\xa5\x10?\xebsw?\xfe\xa8W?\x03\x8a\x1b?\xd9\xf6p?\xb1\x19\x9e=\xb3$v>\x14E'?\x06fi?\x98\x89\xe1>\xcev\x18>g\xcc\xa0>"'

=== REDIS BUG REPORT START: Cut & paste starting from here ===
884185:M 18 Nov 2023 17:16:37.780 # Redis 7.2.1 crashed by signal: 4, si_code: 2
884185:M 18 Nov 2023 17:16:37.780 # Crashed running the instruction at: 0x7fa5515946ad

------ STACK TRACE ------
EIP:
/opt/redis-work/lib/redisearch.so(_Z35FP32_InnerProductSIMD16Ext_SSE_implPKvS0_m+0xd)[0x7fa5515946ad]
------ MODULES INFO OUTPUT ------
# search_version^M
search_version:2.6.5^M
search_redis_version:7.2.1 - oss^M
^M
# search_index^M
search_number_of_indexes:1^M
^M
# search_fields_statistics^M
search_fields_numeric:Numeric=1^M
search_fields_tag:Tag=1^M
search_fields_vector:Vector=1,Flat=1^M
^M
# search_dialect_statistics^M
search_dialect_1:0^M
search_dialect_2:1^M
search_dialect_3:0^M
^M
# search_runtime_configurations^M
search_concurrent_mode:OFF^M
search_enableGC:ON^M
search_minimal_term_prefix:2^M
search_maximal_prefix_expansions:200^M
search_query_timeout_ms:500^M
search_timeout_policy:return^M
search_cursor_read_size:1000^M
search_cursor_max_idle_time:300000^M
search_max_doc_table_size:1000000^M
search_max_search_results:1000000^M
search_max_aggregate_results:-1^M
search_search_pool_size:20^M
search_index_pool_size:8^M
search_gc_scan_size:100^M
search_min_phonetic_term_length:3^M
**To Reproduce**
query = ( Query("@tag: {foo}=>[KNN 2 @vector $vec as score]")
          .return_fields("id", "num", "tag", "score")
          .paging(0, 2)
          .dialect(2)
        )
query_params = {
    "vec": np.random.rand(VECTOR_DIMENSIONS).astype(np.float32).tobytes()
}

import traceback
try:
    res = conn.ft(INDEX_NAME).search(query, query_params).docs
    print(res)
except Exception as e:
    print(traceback.format_exc())
conn.close()
Traceback (most recent call last):
  File "D:\MyPython\cp310\source\tt.py", line 141, in <module>
    res = conn.ft(INDEX_NAME).search(query, query_params).docs
  File "D:\MyPython\cp310\lib\site-packages\redis\commands\search\commands.py", line 501, in search
    res = self.execute_command(SEARCH_CMD, *args)
  File "D:\MyPython\cp310\lib\site-packages\redis\client.py", line 536, in execute_command
    return conn.retry.call_with_retry(
  File "D:\MyPython\cp310\lib\site-packages\redis\retry.py", line 49, in call_with_retry
    fail(error)
  File "D:\MyPython\cp310\lib\site-packages\redis\client.py", line 540, in <lambda>
    lambda error: self._disconnect_raise(conn, error),
  File "D:\MyPython\cp310\lib\site-packages\redis\client.py", line 526, in _disconnect_raise
    raise error
  File "D:\MyPython\cp310\lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
  File "D:\MyPython\cp310\lib\site-packages\redis\client.py", line 537, in <lambda>
    lambda: self._send_command_parse_response(
  File "D:\MyPython\cp310\lib\site-packages\redis\client.py", line 513, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "D:\MyPython\cp310\lib\site-packages\redis\client.py", line 553, in parse_response
    response = connection.read_response()
  File "D:\MyPython\cp310\lib\site-packages\redis\connection.py", line 500, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "D:\MyPython\cp310\lib\site-packages\redis\_parsers\hiredis.py", line 124, in read_response
    self.read_from_socket()
  File "D:\MyPython\cp310\lib\site-packages\redis\_parsers\hiredis.py", line 86, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: linux stream 9
 - CPU model 
 - Version/branch [e.g. 1.2.2]

**Additional context**
redis-server --check-system, output: ok

**Comment by jackchentzh** [comment]
the server access by acl.

**Comment by jackchentzh** [comment]
non-vector search work well with rediSearch.

**Comment by GuyAv46** [comment]
Are you running your server on a VM by chance? We had similar issues before, seems like CPU permissions between the VM and the hardware

**Comment by jackchentzh** [comment]
running on ecs clound server
