### ISSUE TITLE
[BUG] RediSearch HNSW indexing deadlock?

### ISSUE THREAD

**Issue by Veid** [RediSearch/RediSearch#4574]
I think the redis-stack-server is running into a deadlock. Some info about data and index I'm working with:

* ~1.07M hashes
* One of the fields in the hash can be a very long comma-separated string, call it `pid`. The max is around ~700k comma separated numbers. Then I'm using this as a Tag Field in RediSearch as a filter.
  * I update this tag field regularly probably an average of 1 update per second, sometimes more. The update is always appending values, by first reading the field and client-side reconstructing it as a set with the new value added.
    * CPU usage is quite high while this process is running the updates. `thread_pool_0` nearly constantly at 80-100% and spikes in the main process.
  * I suspect I'm abusing Tag Fields and redis can't really do this?
* I also have a 512dim vector field.
* Data + HNSW index uses ~20GB of ram

---

**Stack trace**

```
(gdb) bt
#0  __futex_abstimed_wait_common (cancel=false, private=0, abstime=0x0, clockid=0, expected=2, futex_word=0x719348af0608) at ./nptl/futex-internal.c:103
#1  __GI___futex_abstimed_wait64 (futex_word=futex_word@entry=0x719348af0608, expected=expected@entry=2, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:128
#2  0x000071939ee9b315 in __pthread_rwlock_wrlock_full64 (abstime=0x0, clockid=0, rwlock=0x719348af0600) at ./nptl/pthread_rwlock_common.c:829
#3  ___pthread_rwlock_wrlock (rwlock=0x719348af0600) at ./nptl/pthread_rwlock_wrlock.c:26
#4  0x000071939dcfaa8a in TieredHNSWIndex<float, float>::deleteVector(unsigned long) () from /opt/redis-stack/lib/redisearch.so
#5  0x000071939dbaa561 in Indexer_Process () from /opt/redis-stack/lib/redisearch.so
#6  0x000071939dbaaa35 in Indexer_Add () from /opt/redis-stack/lib/redisearch.so
#7  0x000071939db90af1 in Document_AddToIndexes () from /opt/redis-stack/lib/redisearch.so
#8  0x000071939dbe3805 in IndexSpec_UpdateDoc () from /opt/redis-stack/lib/redisearch.so
#9  0x000071939dbe3fe2 in Indexes_UpdateMatchingWithSchemaRules () from /opt/redis-stack/lib/redisearch.so
#10 0x000071939dbb77e8 in HashNotificationCallback () from /opt/redis-stack/lib/redisearch.so
#11 0x00005d56e7f89cff in moduleNotifyKeyspaceEvent (type=64, event=0x5d56e809c7f9 "hset", key=0x719387053e00, dbid=0) at /__w/redis-stack/redis-stack/redis/src/module.c:8724
#12 0x00005d56e7f54f1c in moduleNotifyKeyspaceEvent (dbid=0, key=0x719387053e00, event=0x5d56e809c7f9 "hset", type=64) at /__w/redis-stack/redis-stack/redis/src/module.c:8681
#13 notifyKeyspaceEvent (type=64, type=64, event=0x5d56e809c7f9 "hset", key=0x719387053e00, dbid=0) at /__w/redis-stack/redis-stack/redis/src/notify.c:114
#14 0x00005d56e7ef7209 in hsetCommand (c=0x71939e962a00) at /__w/redis-stack/redis-stack/redis/src/t_hash.c:631
#15 0x00005d56e7e86226 in call (c=c@entry=0x71939e962a00, flags=flags@entry=3) at /__w/redis-stack/redis-stack/redis/src/server.c:3519
#16 0x00005d56e7e87559 in processCommand (c=0x71939e962a00) at /__w/redis-stack/redis-stack/redis/src/server.c:4160
#17 0x00005d56e7eac387 in processCommandAndResetClient (c=0x71939e962a00) at /__w/redis-stack/redis-stack/redis/src/networking.c:2466
#18 processInputBuffer (c=0x71939e962a00) at /__w/redis-stack/redis-stack/redis/src/networking.c:2574
#19 0x00005d56e7eac908 in readQueryFromClient (conn=<optimized out>) at /__w/redis-stack/redis-stack/redis/src/networking.c:2713
#20 0x00005d56e7fb5b9c in callHandler (handler=<optimized out>, conn=0x71939eb80840) at /__w/redis-stack/redis-stack/redis/src/connhelpers.h:79
#21 connSocketEventHandler (el=<optimized out>, fd=<optimized out>, clientData=0x71939eb80840, mask=<optimized out>) at /__w/redis-stack/redis-stack/redis/src/socket.c:298
#22 0x00005d56e7e7bdd9 in aeProcessEvents (flags=27, eventLoop=0x71939eb90140) at /__w/redis-stack/redis-stack/redis/src/ae.c:436
#23 aeMain (eventLoop=0x71939eb90140) at /__w/redis-stack/redis-stack/redis/src/ae.c:496
#24 0x00005d56e7e7063f in main (argc=2, argv=<optimized out>) at /__w/redis-stack/redis-stack/redis/src/server.c:7360
```

---

**To Reproduce**
After inserting the data and the index is fully created, I start a queue process that updates the tag field in my hashes. RediSearch will run this way with no issues besides high CPU usage. Once I start running vector search queries, at some point redis-stack-server will stop responding. CPU usage drops to 0% and the `bt` looks like above. The search queries look like this:

```
(@count:[5000 +inf] @avg:[2 +inf] -@pid:{111111})=>[KNN 64 @text_emb $BLOB AS vec_score]
```

Where `$BLOB` is a 512dim byte blob. `pid` is the large tag field...

---

**Environment**
 - OS: Ubuntu 22.04.4 LTS
 - CPU model: Intel(R) Xeon(R) Platinum 8151 CPU @ 3.40GHz
 - Redis versions:
 
 ```
redis_version:7.2.4
gcc_version:11.4.0

# Modules
module:name=timeseries,ver=11011,api=1,filters=0,usedby=[],using=[],options=[]
module:name=ReJSON,ver=20609,api=1,filters=0,usedby=[search],using=[],options=[handle-io-errors]
module:name=search,ver=20812,api=1,filters=0,usedby=[],using=[ReJSON],options=[handle-io-errors]
module:name=redisgears_2,ver=20019,api=1,filters=0,usedby=[],using=[],options=[]
module:name=RedisCompat,ver=1,api=1,filters=0,usedby=[],using=[],options=[]
module:name=bf,ver=20612,api=1,filters=0,usedby=[],using=[],options=[]
```

**Additional context**
I have a ~20GB core dump, ~11GB gzip -- I can provide that if necessary.

**Comment by GuyAv46** [comment]
Hey @Veid, thanks for reporting!
This is a known issue in RediSearch 2.8.12; a fix was introduced in version [2.8.13](https://github.com/RediSearch/RediSearch/releases/tag/v2.8.13) (#4496, #4498)
