### ISSUE TITLE
[BUG] Redis Server Freeze/Unresponsive

### ISSUE THREAD

**Issue by simon1990zcs** [RediSearch/RediSearch#4951]
**Describe the bug**
in some cases, redis server just become freeze and unresponsive, failed to connect to redis server at all, and can't log in from redis insight at all.
I don't know what exactly the issue, but based on timing, it could be one client disconnect from redis server, when the client is restarting itself. (FYI, the client is using Jedis library) any concern if the client is not shutdown graceful/properly.
from the stack race below, seems like it might related to Search Indexing, while we created hundreds of temporary indexes from client using Jedis library, not sure if this raised any alarm.

**To Reproduce**
don't have reproduce steps

**Expected behavior**
redis server should be responsive always

**Screenshots**
none

**Environment (please complete the following information):**
 - OS: CentOS Linux release 7.6.1810 (Core)
 - CPU model: Intel(R) Xeon(R) Gold 6254 CPU @ 3.10GHz
 - Version/branch: 7.2.0

**Additional context**

stack trace when frozen:
```
#0  0x00007f8d352332ce in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
#1  0x00007f8d2c69956b in RedisSearchCtx_LockSpecWrite () from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redisearch.so
#2  0x00007f8d2c6ab45b in IndexSpec_DeleteDoc () from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redisearch.so
#3  0x00007f8d2c6abbfa in Indexes_DeleteMatchingWithSchemaRules () from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redisearch.so
#4  0x00007f8d2c681b16 in HashNotificationCallback () from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redisearch.so
#5  0x00000000004ff95f in moduleNotifyKeyspaceEvent.part.97.58377 (type=256, event=0x61abbf "expired", key=0x7f8c3d4ad620, dbid=0) at module.c:8724
#6  0x000000000050a445 in moduleNotifyKeyspaceEvent (dbid=0, key=0x7f8c3d4ad620, event=0x61abbf "expired", type=256) at notify.c:145
#7  notifyKeyspaceEvent (type=<optimized out>, event=<optimized out>, key=<optimized out>, dbid=<optimized out>, dbid=<optimized out>, key=<optimized out>, event=<optimized out>) at notify.c:114
#8  0x000000000050e6ea in deleteExpiredKeyAndPropagate (keyobj=0x7f8c3d4ad620, db=0x7f8d33531000) at db.c:1686
#9  expireIfNeeded.part.6.12916 (db=0x7f8d33531000, key=0x7f8c3d4ad620) at db.c:1813
#10 0x000000000050eb44 in expireIfNeeded (flags=<optimized out>, key=0x7f8c3d4ad620, db=0x7f8d33531000) at networking.c:4077
#11 lookupKey (db=0x7f8d33531000, key=0x7f8c3d4ad620, flags=0) at db.c:107
#12 0x0000000000516cdf in lookupKeyReadWithFlags (flags=0, key=0x7f8c3d4ad620, db=<optimized out>) at db.c:153
#13 RM_OpenKey (ctx=0x7ffcc4b3b790, keyname=0x7f8c3d4ad620, mode=1) at module.c:4005
#14 0x00007f8d2adad201 in redis_module::context::Context::open_key::h6e9944a47573023b ()
   from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/rejson.so
#15 0x00007f8d2ad3a6bd in rejson::c_api::json_api_open_key_internal::heef0c3554720f6d6 ()
   from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/rejson.so
#16 0x00007f8d2c6a1133 in getKeyCommonJSON () from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redisearch.so
#17 0x00007f8d2c69f8aa in loadIndividualKeys () from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redisearch.so
#18 0x00007f8d2c69e3b7 in rploaderNext () from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redisearch.so
#19 0x00007f8d2c640a5a in rpevalNext_project () from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redisearch.so
#20 0x00007f8d2c64abbd in Grouper_rpAccum () from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redisearch.so
#21 0x00007f8d2c69ec2e in rpsortNext_Accum () from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redisearch.so
#22 0x00007f8d2c638365 in sendChunk () from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redisearch.so
#23 0x00007f8d2c638bd7 in AREQ_Execute () from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redisearch.so
#24 0x00007f8d2c6396b3 in RSAggregateCommand () from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redisearch.so
#25 0x00000000004ffa9c in RedisModuleCommandDispatcher (c=0x7f8affc0b500) at module.c:917
#26 0x0000000000539808 in call (c=c@entry=0x7f8affc0b500, flags=flags@entry=3) at server.c:3519
#27 0x000000000053bb33 in processCommand (c=0x7f8affc0b500) at server.c:4160
#28 0x000000000057b7c7 in processCommandAndResetClient (c=0x7f8affc0b500) at networking.c:2466
#29 processInputBuffer (c=c@entry=0x7f8affc0b500) at networking.c:2574
#30 0x000000000057bf73 in readQueryFromClient (conn=<optimized out>) at networking.c:2713
#31 0x00000000004b1f55 in callHandler (handler=<optimized out>, conn=0x7f8a70b5df00) at connhelpers.h:79
#32 tlsHandleEvent (conn=0x7f8a70b5df00, mask=<optimized out>) at tls.c:720
#33 0x00000000004d5ab9 in aeProcessEvents (flags=27, eventLoop=0x7f8d3342a1e0) at ae.c:436
#34 aeMain (eventLoop=0x7f8d3342a1e0) at ae.c:496
#35 0x0000000000457210 in main (argc=<optimized out>, argv=0x7ffcc4b3bbc8) at server.c:7360
```

info register:
```
rax            0xfffffffffffffe00       -512
rbx            0x7ffcc4b3b100   140723608596736
rcx            0xffffffffffffffff       -1
rdx            0x0      0
rsi            0x80     128
rdi            0x7f8d20b28dac   140244115688876
rbp            0x7f8d20b28c00   0x7f8d20b28c00
rsp            0x7ffcc4b3b0d8   0x7ffcc4b3b0d8
r8             0x7da    2010
r9             0x7f8d33400ff0   140244426952688
r10            0x0      0
r11            0x206    518
r12            0x7ffcc4b3b210   140723608597008
r13            0x7f8c3d4ad620   140240300463648
r14            0x7da    2010
r15            0x7ffcc4b3b100   140723608596736
rip            0x7f8d352332ce   0x7f8d352332ce <pthread_rwlock_wrlock+62>
eflags         0x206    [ PF IF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
```

redis server config:
```
maxmemory 300gb
maxmemory-policy allkeys-lru
appendonly no
save ""
timeout 0
io-threads 4
loglevel notice
logfile path

user admin on +@all ~* #somehash
user readOnly on +@read +info +ping +json.get +ts.range ~* #somehash
user readWrite on +@all -@dangerous +info +ping ~* #somehash
user default off

port 0
tls-port 6379
tls-cert-file path1
tls-key-file path2
tls-ca-cert-file path3
tls-auth-clients no
```
redis server log (notice): not any useful log around freezing time
```
38578:C 20 Aug 2024 12:47:08.767 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
38578:C 20 Aug 2024 12:47:08.768 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
38578:C 20 Aug 2024 12:47:08.768 * Redis version=7.2.1, bits=64, commit=00000000, modified=0, pid=38578, just started
38578:C 20 Aug 2024 12:47:08.769 * Configuration loaded
38578:M 20 Aug 2024 12:47:08.770 * monotonic clock: POSIX clock_gettime
38578:M 20 Aug 2024 12:47:08.772 * Running mode=standalone, port=6379.
38578:M 20 Aug 2024 12:47:08.773 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
38578:M 20 Aug 2024 12:47:08.777 * <search> Redis version found by RedisSearch : 7.2.1 - oss
38578:M 20 Aug 2024 12:47:08.778 * <search> RediSearch version 2.8.4 (Git=HEAD-7797d39)
38578:M 20 Aug 2024 12:47:08.778 * <search> Low level api version 1 initialized successfully
38578:M 20 Aug 2024 12:47:08.779 * <search> concurrent writes: OFF, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  10000, search pool size: 20, index pool size: 8, 
38578:M 20 Aug 2024 12:47:08.780 * <search> Initialized thread pools!
38578:M 20 Aug 2024 12:47:08.780 * <search> Enabled role change notification
38578:M 20 Aug 2024 12:47:08.781 * Module 'search' loaded from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redisearch.so
38578:M 20 Aug 2024 12:47:08.783 * <timeseries> RedisTimeSeries version 11006, git_sha=2a4739648bbe771fc60561b37fbc7f3ca4cc4f24
38578:M 20 Aug 2024 12:47:08.784 * <timeseries> Redis version found by RedisTimeSeries : 7.2.1 - oss
38578:M 20 Aug 2024 12:47:08.785 * <timeseries> loaded default CHUNK_SIZE_BYTES policy: 4096
38578:M 20 Aug 2024 12:47:08.786 * <timeseries> loaded server DUPLICATE_POLICY: block
38578:M 20 Aug 2024 12:47:08.786 * <timeseries> Setting default series ENCODING to: compressed
38578:M 20 Aug 2024 12:47:08.787 * <timeseries> Detected redis oss
38578:M 20 Aug 2024 12:47:08.788 * Module 'timeseries' loaded from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redistimeseries.so
38578:M 20 Aug 2024 12:47:08.790 * <ReJSON> Created new data type 'ReJSON-RL'
38578:M 20 Aug 2024 12:47:08.791 * <ReJSON> version: 20606 git sha: unknown branch: unknown
38578:M 20 Aug 2024 12:47:08.791 * <ReJSON> Exported RedisJSON_V1 API
38578:M 20 Aug 2024 12:47:08.792 * <ReJSON> Exported RedisJSON_V2 API
38578:M 20 Aug 2024 12:47:08.792 * <ReJSON> Exported RedisJSON_V3 API
38578:M 20 Aug 2024 12:47:08.793 * <ReJSON> Exported RedisJSON_V4 API
38578:M 20 Aug 2024 12:47:08.793 * <ReJSON> Enabled diskless replication
38578:M 20 Aug 2024 12:47:08.794 * Module 'ReJSON' loaded from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/rejson.so
38578:M 20 Aug 2024 12:47:08.794 * <search> Acquired RedisJSON_V4 API
38578:M 20 Aug 2024 12:47:08.796 * <bf> RedisBloom version 2.6.3 (Git=unknown)
38578:M 20 Aug 2024 12:47:08.797 * Module 'bf' loaded from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redisbloom.so
38578:M 20 Aug 2024 12:47:08.799 * <redisgears_2> Created new data type 'GearsType'
38578:M 20 Aug 2024 12:47:08.800 * <redisgears_2> Detected redis oss
38578:M 20 Aug 2024 12:47:08.801 # <redisgears_2> could not initialize RedisAI_InitError

38578:M 20 Aug 2024 12:47:08.801 * <redisgears_2> Failed loading RedisAI API.
38578:M 20 Aug 2024 12:47:08.802 * <redisgears_2> RedisGears v2.0.12, sha='716eb57fcfc2d383ec0925a59563f1bf69e2caa3', build_type='release', built_for='Linux-rhel7.x86_64'.
38578:M 20 Aug 2024 12:47:08.805 * <redisgears_2> Registered backend: js.
38578:M 20 Aug 2024 12:47:08.806 * Module 'redisgears_2' loaded from /home/svc_cathedral/nomad/pxstlccath008/alloc/fa9f504b-64e7-d510-1b7c-f56885fb4dca/redis-task/local/redis-stack-server-7.2.0-v2/lib/redisgears.so
38578:M 20 Aug 2024 12:47:08.807 * The user 'default' is disabled (there is no 'on' modifier in the user description). Make sure this is not a configuration error.
38578:M 20 Aug 2024 12:47:08.819 * Server initialized
38578:M 20 Aug 2024 12:47:08.821 * Ready to accept connections tls
38578:M 20 Aug 2024 14:32:35.458 # Error accepting a client connection: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol (addr=127.0.0.1:54758 laddr=127.0.0.1:6379)
38578:M 20 Aug 2024 14:32:35.459 # Error accepting a client connection: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol (addr=10.49.30.56:37694 laddr=10.49.30.56:6379)
38578:M 20 Aug 2024 20:37:35.448 # Error accepting a client connection: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol (addr=127.0.0.1:34328 laddr=127.0.0.1:6379)
38578:M 20 Aug 2024 20:37:35.450 # Error accepting a client connection: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol (addr=10.49.30.56:45496 laddr=10.49.30.56:6379)
```

**Comment by nafraf** [comment]
Hi @simon1990zcs, thanks for the report.
Could you try with a more recent version of RediSearch and try to reproduce the error?

**Comment by simon1990zcs** [comment]
> Hi @simon1990zcs, thanks for the report. Could you try with a more recent version of RediSearch and try to reproduce the error?

I couldn't start latest version Redis 7.4.0 for some reasons, it complains with some missing files while starting redis. 
I believe 7.2.0 version is not that out dated, do you have any insights what issue it could be?

**Comment by nafraf** [comment]
I was suggesting to start updating the RediSearch module only, you are using v2.8.4, but [v2.8.17](https://github.com/RediSearch/RediSearch/releases/tag/v2.8.17) was released last week.

> I couldn't start latest version Redis 7.4.0 for some reasons, it complains with some missing files while starting redis.

If you want to try 7.4.0, it's OK, could you post the error messages?

**Comment by simon1990zcs** [comment]
when I try to use newer version of RedisSearch module, similar error when I try to start Redis 7.4, it complains 
```
# Module /path_to_redis/lib/redisearch.so failed to load: /lib64/libc.so.6: version `GLIBC_2.25' not found
```
Seems like there is some sort of in-compatibility between newer version of Redis/RedisSearch and my system.

**Comment by nafraf** [comment]
> Seems like there is some sort of in-compatibility between newer version of RedisServer and my system.

Correct. Redis Server supports RHEL compatible distributions, but Redis Server 7.4 does not support RHEL7.
This is the list of [supported platforms](https://redis.io/docs/latest/operate/rs/installing-upgrading/install/plan-deployment/supported-platforms/)

**Comment by simon1990zcs** [comment]
Unfortunately, after trying RedisSearch module **v2.8.15** with Redis 7.2, the issue still persist. 
(I am aware that you told me to try latest RedisSearch 2.8.17, but v2.8.15 is the latest RedisSearch module I could find from pre-compiled RedisStack. due to some reason, I can't compile module from source code. If you still wish me to try v2.8.17, can you point me where I can download pre-compiled module) 

Also, I believe this could be related to JSON together with Temporary SearchIndex. 
below are simplified upload statement:
```
jedis.ftList(), used to check whether do I need to create new index or not
loop for each data {
  pipeline.ftCreate(), create a temporary index
  pipeline.jsonSet(keyName, someDeepStructureJsonObject)
  pipeline.expire(keyName, someTime)
}
```

stack trace while freeze:
```
#0  0x00007f1ab16622ce in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
#1  0x00007f1aa8a8364b in RedisSearchCtx_LockSpecWrite ()
   from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisearch.so
#2  0x00007f1aa8a95dfb in IndexSpec_DeleteDoc ()
   from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisearch.so
#3  0x00007f1aa8a965da in Indexes_DeleteMatchingWithSchemaRules ()
   from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisearch.so
#4  0x00007f1aa8a6b4fe in HashNotificationCallback ()
   from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisearch.so
#5  0x00000000004ff95f in moduleNotifyKeyspaceEvent.part.97.58377 (type=256, event=0x61abbf "expired", key=0x7f19c0139760, dbid=0) at module.c:8724
#6  0x000000000050a445 in moduleNotifyKeyspaceEvent (dbid=0, key=0x7f19c0139760, event=0x61abbf "expired", type=256) at notify.c:145
#7  notifyKeyspaceEvent (type=<optimized out>, event=<optimized out>, key=<optimized out>, dbid=<optimized out>, dbid=<optimized out>, key=<optimized out>, event=<optimized out>) at notify.c:114
#8  0x000000000050e6ea in deleteExpiredKeyAndPropagate (keyobj=0x7f19c0139760, db=0x7f1aaf944000) at db.c:1686
#9  expireIfNeeded.part.6.12916 (db=0x7f1aaf944000, key=0x7f19c0139760) at db.c:1813
#10 0x000000000050eb44 in expireIfNeeded (flags=<optimized out>, key=0x7f19c0139760, db=0x7f1aaf944000) at networking.c:4077
#11 lookupKey (db=0x7f1aaf944000, key=0x7f19c0139760, flags=0) at db.c:107
#12 0x0000000000516cdf in lookupKeyReadWithFlags (flags=0, key=0x7f19c0139760, db=<optimized out>) at db.c:153
#13 RM_OpenKey (ctx=0x7ffdfa623810, keyname=0x7f19c0139760, mode=1) at module.c:4005
#14 0x00007f1aa7188201 in redis_module::context::Context::open_key::h6e9944a47573023b ()
   from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/rejson.so
#15 0x00007f1aa71156bd in rejson::c_api::json_api_open_key_internal::heef0c3554720f6d6 ()
   from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/rejson.so
#16 0x00007f1aa8a8b713 in getKeyCommonJSON ()
   from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisearch.so
#17 0x00007f1aa8a89d7a in loadIndividualKeys ()
   from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisearch.so
#18 0x00007f1aa8a88785 in rploaderNext () from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisearch.so
#19 0x00007f1aa8a282aa in rpevalNext_project ()
   from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisearch.so
#20 0x00007f1aa8a32b6d in Grouper_rpAccum ()
   from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisearch.so
#21 0x00007f1aa8a8908e in rpsortNext_Accum ()
   from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisearch.so
#22 0x00007f1aa8a1f317 in startPipeline () from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisearch.so
#23 0x00007f1aa8a1f98e in sendChunk () from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisearch.so
#24 0x00007f1aa8a20317 in AREQ_Execute () from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisearch.so
#25 0x00007f1aa8a20d5b in RSAggregateCommand ()
   from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisearch.so
#26 0x00000000004ffa9c in RedisModuleCommandDispatcher (c=0x7f1a7e62aa00) at module.c:917
#27 0x0000000000539808 in call (c=c@entry=0x7f1a7e62aa00, flags=flags@entry=3) at server.c:3519
#28 0x000000000053bb33 in processCommand (c=0x7f1a7e62aa00) at server.c:4160
#29 0x000000000057b7c7 in processCommandAndResetClient (c=0x7f1a7e62aa00) at networking.c:2466
#30 processInputBuffer (c=c@entry=0x7f1a7e62aa00) at networking.c:2574
#31 0x000000000057bf73 in readQueryFromClient (conn=<optimized out>) at networking.c:2713
#32 0x00000000004b1f55 in callHandler (handler=<optimized out>, conn=0x7f19c2ef04a0) at connhelpers.h:79
#33 tlsHandleEvent (conn=0x7f19c2ef04a0, mask=<optimized out>) at tls.c:720
#34 0x00000000004d5ab9 in aeProcessEvents (flags=27, eventLoop=0x7f1aaf82a1e0) at ae.c:436
#35 aeMain (eventLoop=0x7f1aaf82a1e0) at ae.c:496
#36 0x0000000000457210 in main (argc=<optimized out>, argv=0x7ffdfa623c48) at server.c:7360
```

info register:
```
rax            0xfffffffffffffe00       -512
rbx            0x7ffdfa6230a0   140728804192416
rcx            0xffffffffffffffff       -1
rdx            0x0      0
rsi            0x80     128
rdi            0x7f1a9cc4ffac   139752276033452
rbp            0x7f1a9cc4fe00   0x7f1a9cc4fe00
rsp            0x7ffdfa623078   0x7ffdfa623078
r8             0x4fa    1274
r9             0x7f1aaf8016e8   139752590284520
r10            0x0      0
r11            0x206    518
r12            0x7ffdfa6231b0   140728804192688
r13            0x7f19c0139760   139748573419360
r14            0x4fa    1274
r15            0x7ffdfa6230a0   140728804192416
rip            0x7f1ab16622ce   0x7f1ab16622ce <pthread_rwlock_wrlock+62>
eflags         0x206    [ PF IF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
```

server log:
```
40875:C 28 Aug 2024 13:42:59.827 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
40875:C 28 Aug 2024 13:42:59.828 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
40875:C 28 Aug 2024 13:42:59.829 * Redis version=7.2.1, bits=64, commit=00000000, modified=0, pid=40875, just started
40875:C 28 Aug 2024 13:42:59.829 * Configuration loaded
40875:M 28 Aug 2024 13:42:59.831 * monotonic clock: POSIX clock_gettime
40875:M 28 Aug 2024 13:42:59.833 * Running mode=standalone, port=6379.
40875:M 28 Aug 2024 13:42:59.834 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
40875:M 28 Aug 2024 13:42:59.841 * <search> Redis version found by RedisSearch : 7.2.1 - oss
40875:M 28 Aug 2024 13:42:59.842 * <search> RediSearch version 2.8.15 (Git=2.8-8ed4a83)
40875:M 28 Aug 2024 13:42:59.843 * <search> Low level api version 1 initialized successfully
40875:M 28 Aug 2024 13:42:59.844 * <search> concurrent writes: OFF, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  10000, search pool size: 20, index pool size: 8, 
40875:M 28 Aug 2024 13:42:59.845 * <search> Initialized thread pools!
40875:M 28 Aug 2024 13:42:59.846 * <search> Enabled role change notification
40875:M 28 Aug 2024 13:42:59.847 * Module 'search' loaded from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisearch.so
40875:M 28 Aug 2024 13:42:59.852 * <timeseries> RedisTimeSeries version 11006, git_sha=2a4739648bbe771fc60561b37fbc7f3ca4cc4f24
40875:M 28 Aug 2024 13:42:59.853 * <timeseries> Redis version found by RedisTimeSeries : 7.2.1 - oss
40875:M 28 Aug 2024 13:42:59.854 * <timeseries> loaded default CHUNK_SIZE_BYTES policy: 4096
40875:M 28 Aug 2024 13:42:59.855 * <timeseries> loaded server DUPLICATE_POLICY: block
40875:M 28 Aug 2024 13:42:59.856 * <timeseries> Setting default series ENCODING to: compressed
40875:M 28 Aug 2024 13:42:59.856 * <timeseries> Detected redis oss
40875:M 28 Aug 2024 13:42:59.858 * Module 'timeseries' loaded from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redistimeseries.so
40875:M 28 Aug 2024 13:42:59.861 * <ReJSON> Created new data type 'ReJSON-RL'
40875:M 28 Aug 2024 13:42:59.862 * <ReJSON> version: 20606 git sha: unknown branch: unknown
40875:M 28 Aug 2024 13:42:59.862 * <ReJSON> Exported RedisJSON_V1 API
40875:M 28 Aug 2024 13:42:59.863 * <ReJSON> Exported RedisJSON_V2 API
40875:M 28 Aug 2024 13:42:59.864 * <ReJSON> Exported RedisJSON_V3 API
40875:M 28 Aug 2024 13:42:59.865 * <ReJSON> Exported RedisJSON_V4 API
40875:M 28 Aug 2024 13:42:59.865 * <ReJSON> Enabled diskless replication
40875:M 28 Aug 2024 13:42:59.866 * Module 'ReJSON' loaded from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/rejson.so
40875:M 28 Aug 2024 13:42:59.867 * <search> Acquired RedisJSON_V4 API
40875:M 28 Aug 2024 13:42:59.869 * <bf> RedisBloom version 2.6.3 (Git=unknown)
40875:M 28 Aug 2024 13:42:59.870 * Module 'bf' loaded from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisbloom.so
40875:M 28 Aug 2024 13:42:59.873 * <redisgears_2> Created new data type 'GearsType'
40875:M 28 Aug 2024 13:42:59.875 * <redisgears_2> Detected redis oss
40875:M 28 Aug 2024 13:42:59.876 # <redisgears_2> could not initialize RedisAI_InitError

40875:M 28 Aug 2024 13:42:59.877 * <redisgears_2> Failed loading RedisAI API.
40875:M 28 Aug 2024 13:42:59.877 * <redisgears_2> RedisGears v2.0.12, sha='716eb57fcfc2d383ec0925a59563f1bf69e2caa3', build_type='release', built_for='Linux-rhel7.x86_64'.
40875:M 28 Aug 2024 13:42:59.881 * <redisgears_2> Registered backend: js.
40875:M 28 Aug 2024 13:42:59.882 * Module 'redisgears_2' loaded from /home/user/nomad/pxstlccath005/alloc/0b4e8e3f-9c68-ec7c-68fa-f545b9b76b11/redis-task/local/redis-stack-server-7.2.0-v2-customized/lib/redisgears.so
40875:M 28 Aug 2024 13:42:59.883 * The user 'default' is disabled (there is no 'on' modifier in the user description). Make sure this is not a configuration error.
40875:M 28 Aug 2024 13:42:59.901 * Server initialized
40875:M 28 Aug 2024 13:42:59.902 * <search> Loading event starts
40875:M 28 Aug 2024 13:42:59.903 * <redisgears_2> Got a loading start event, clear the entire functions data.
40875:M 28 Aug 2024 13:42:59.905 * Loading RDB produced by version 7.2.1
40875:M 28 Aug 2024 13:42:59.906 * RDB age 73051 seconds
40875:M 28 Aug 2024 13:42:59.907 * RDB memory usage when created 24.08 Mb
40875:M 28 Aug 2024 13:42:59.935 * Done loading RDB, keys loaded: 3, keys expired: 0.
40875:M 28 Aug 2024 13:42:59.936 * <search> Loading event ends
40875:M 28 Aug 2024 13:42:59.937 * <redisgears_2> Loading finished, re-enable key space notificaitons.
40875:M 28 Aug 2024 13:42:59.938 * DB loaded from disk: 0.036 seconds
40875:M 28 Aug 2024 13:42:59.938 * Ready to accept connections tls
40875:M 28 Aug 2024 14:43:00.154 * Replication backlog freed after 3600 seconds without connected replicas.
40875:M 28 Aug 2024 19:14:51.116 # Error accepting a client connection: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
40875:M 28 Aug 2024 19:14:51.119 # Error accepting a client connection: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
```

**Comment by DvirDukhan** [comment]
@simon1990zcs please upgrade your RedisJSON module to>= 2.6.9 https://github.com/RedisJSON/RedisJSON/releases/tag/v2.6.9

**Comment by simon1990zcs** [comment]
Thanks for updating, glad this issue was filed and fixed already. 
Very unfortunately, RedisJSON stop support RHEL7 since v2.6.8.
