### ISSUE TITLE
[BUG] can search records after searching but the data is nil

### ISSUE THREAD

**Issue by musiye14** [RediSearch/RediSearch#5034]
**Describe the bug**
 I can get the data but search is nil I don't know what's the reason.

**To Reproduce**
```
FT.SEARCH my_index "*"
```
```
1) (integer) 31
 2) "log_json_v1:32"
 3) (nil)
 4) "log_json_v1:25"
 5) (nil)
 6) "log_json_v1:10"
 7) (nil)
 8) "log_json_v1:101"
 9) (nil)
10) "log_json_v1:109"
11) (nil)
12) "log_json_v1:50"
13) (nil)
14) "log_json_v1:83"
15) (nil)
16) "log_json_v1:72"
17) (nil)
18) "log_json_v1:87"
19) (nil)
20) "log_json_v1:76"
21) (nil)
```

the get
```
JSON.GET log_json_v1:32
"{\"version\":\"32\",\"time\":\"2024-01-31 17:10:12\",\"filelist\":\"Jx3mHelperTray.csproj|1\",\"msg\":\"\xe3\x80\x90\xe9\x85\x8d\xe7\xbd\xae\xe4\xbf\xae\xe6\x94\xb9\xe3\x80\x91 \xe7\x94\x9f\xe6\x88\x90\xe5\x90\x8e\xe5\x88\xa0\xe9\x99\xa4pdb\xe6\x96\x87\xe4\xbb\xb6\",\"listnumber\":\"12345\",\"actions\":\"1\"}"
```

the index info
```
 FT.INFO my_index
 1) index_name
 2) my_index
 3) index_options
 4) (empty array)
 5) index_definition
 6) 1) key_type
    2) JSON
    3) prefixes
    4) 1) log_json_v1:
    5) default_score
    6) "1"
 7) attributes
 8) 1) 1) identifier
       2) $.version
       3) attribute
       4) version
       5) type
       6) TEXT
       7) WEIGHT
       8) "1"
    2) 1) identifier
       2) $.time
       3) attribute
       4) time
       5) type
       6) TEXT
       7) WEIGHT
       8) "1"
    3) 1) identifier
       2) $.actions
       3) attribute
       4) actions
       5) type
       6) TEXT
       7) WEIGHT
       8) "1"
    4) 1) identifier
       2) $.filelist
       3) attribute
       4) filelist
       5) type
       6) TEXT
       7) WEIGHT
       8) "1"
    5) 1) identifier
       2) $.msg
       3) attribute
       4) msg
       5) type
       6) TEXT
       7) WEIGHT
       8) "1"
 9) num_docs
10) (integer) 34
11) max_doc_id
12) (integer) 34
13) num_terms
14) (integer) 393
15) num_records
16) (integer) 722
17) inverted_sz_mb
18) "0.04095458984375"
19) vector_index_sz_mb
20) "0"
21) total_inverted_index_blocks
22) (integer) 44234
23) offset_vectors_sz_mb
24) "0.0012159347534179688"
25) doc_table_size_mb
26) "0.002593994140625"
27) sortable_values_size_mb
28) "0"
29) key_table_size_mb
30) "0.0011892318725585938"
31) tag_overhead_sz_mb
32) "0"
33) text_overhead_sz_mb
34) "0.013117790222167969"
35) total_index_memory_sz_mb
36) "0.06301498413085938"
37) geoshapes_sz_mb
38) "0"
39) records_per_doc_avg
40) "21.235294342041016"
41) bytes_per_record_avg
42) "59.479225158691406"
43) offsets_per_term_avg
44) "1.5900276899337769"
45) offset_bits_per_record_avg
46) "8.885017395019531"
47) hash_indexing_failures
48) (integer) 0
49) total_indexing_time
50) "7.578999996185303"
51) indexing
52) (integer) 0
53) percent_indexed
54) "1"
55) number_of_uses
56) (integer) 8
57) cleaning
58) (integer) 0
59) gc_stats
60)  1) bytes_collected
     2) "0"
     3) total_ms_run
     4) "0"
     5) total_cycles
     6) "0"
     7) average_cycle_time_ms
     8) "nan"
     9) last_run_time_ms
    10) "0"
    11) gc_numeric_trees_missed
    12) "0"
    13) gc_blocks_denied
    14) "0"
61) cursor_stats
62) 1) global_idle
    2) (integer) 0
    3) global_total
    4) (integer) 0
    5) index_capacity
    6) (integer) 128
    7) index_total
    8) (integer) 0
63) dialect_stats
64) 1) dialect_1
    2) (integer) 1
    3) dialect_2
    4) (integer) 0
    5) dialect_3
    6) (integer) 0
    7) dialect_4
    8) (integer) 0
65) Index Errors
66) 1) indexing failures
    2) (integer) 0
    3) last indexing error
    4) N/A
    5) last indexing error key
    6) "N/A"
67) field statistics
68) 1) 1) identifier
       2) $.version
       3) attribute
       4) version
       5) Index Errors
       6) 1) indexing failures
          2) (integer) 0
          3) last indexing error
          4) N/A
          5) last indexing error key
          6) "N/A"
    2) 1) identifier
       2) $.time
       3) attribute
       4) time
       5) Index Errors
       6) 1) indexing failures
          2) (integer) 0
          3) last indexing error
          4) N/A
          5) last indexing error key
          6) "N/A"
    3) 1) identifier
       2) $.actions
       3) attribute
       4) actions
       5) Index Errors
       6) 1) indexing failures
          2) (integer) 0
          3) last indexing error
          4) N/A
          5) last indexing error key
          6) "N/A"
    4) 1) identifier
       2) $.filelist
       3) attribute
       4) filelist
       5) Index Errors
       6) 1) indexing failures
          2) (integer) 0
          3) last indexing error
          4) N/A
          5) last indexing error key
          6) "N/A"
    5) 1) identifier
       2) $.msg
       3) attribute
       4) msg
       5) Index Errors
       6) 1) indexing failures
          2) (integer) 0
          3) last indexing error
          4) N/A
          5) last indexing error key
          6) "N/A"
```

**Expected behavior**
I'd like to see the data displayed properly，Because of nil, I get an error when using python libraries.
```
Traceback (most recent call last):
  File "G:\project\redis\test.py", line 106, in <module>
    get_data()
  File "G:\project\redis\test.py", line 98, in get_data
    res = client.search(query)
  File "G:\app\Python-3.9.6\lib\site-packages\redisearch\client.py", line 529, in search
    return Result(res,
  File "G:\app\Python-3.9.6\lib\site-packages\redisearch\result.py", line 42, in __init__
    dict(izip(map(to_string, res[i + fields_offset][::2]),
TypeError: 'NoneType' object is not subscriptable
```

**Environment (please complete the following information):**
 - redis_version:7.4.0
 - using docker run --name redis-r1 -p 6001:6001 -p 16001:16001 -v  D:\\redis\\config\\master\\redis-stack.conf:/redis-stack.conf -d --restart=always redis/redis-stack-server:latest 
 - docker run --name redis-r1 -p 6002:6002 -p 16002:16002 -v D:\\redis\\config\\master\\redis-stack.conf:/redis-stack.conf -d --restart=always redis/redis-stack-server:latest 
 - docker run --name redis-r1 -p 6003:6003 -p 16003:16003 -v D:\\redis\\config\\master\\redis-stack.conf:/redis-stack.conf -d --restart=always redis/redis-stack-server:latest

**Comment by musiye14** [comment]
I'm using it in cluster mode.

**Comment by shrihari-nasdaq** [comment]
Hi @musiye14 
Can you try adding the returning field path or indexed field alias in your query?

```
FT.SEARCH my_index "*" RETURN 2 time actions
```

**Comment by musiye14** [comment]
```
10.11.185.73:6001> FT.SEARCH my_index "*" RETURN 0
 1) (integer) 34
 2) "log_json_v1:32"
 3) "log_json_v1:25"
 4) "log_json_v1:10"
 5) "log_json_v1:101"
 6) "log_json_v1:109"
 7) "log_json_v1:50"
 8) "log_json_v1:83"
 9) "log_json_v1:72"
10) "log_json_v1:87"
11) "log_json_v1:76"
10.11.185.73:6001> FT.SEARCH my_index "*" RETURN 1 version
 1) (integer) 34
 2) "log_json_v1:32"
 3) (nil)
 4) "log_json_v1:25"
 5) (nil)
 6) "log_json_v1:10"
 7) (nil)
 8) "log_json_v1:101"
 9) (nil)
10) "log_json_v1:109"
11) (nil)
12) "log_json_v1:50"
13) (nil)
14) "log_json_v1:83"
15) (nil)
16) "log_json_v1:72"
17) (nil)
18) "log_json_v1:87"
19) (nil)
20) "log_json_v1:76"
21) (nil)
10.11.185.73:6001> FT.SEARCH my_index "*" RETURN 2 version msg
 1) (integer) 34
 2) "log_json_v1:32"
 3) (nil)
 4) "log_json_v1:25"
 5) (nil)
 6) "log_json_v1:10"
 7) (nil)
 8) "log_json_v1:101"
 9) (nil)
10) "log_json_v1:109"
11) (nil)
12) "log_json_v1:50"
13) (nil)
14) "log_json_v1:83"
15) (nil)
16) "log_json_v1:72"
17) (nil)
18) "log_json_v1:87"
19) (nil)
20) "log_json_v1:76"
21) (nil)
10.11.185.73:6001>
```

**Comment by shrihari-nasdaq** [comment]
Hi @musiye14 
I was able to retrieve values for sample JSON you have shared.

I have created the following sample index
```
FT.CREATE my_index ON JSON PREFIX 1 log_json_v1:  SCHEMA $.version AS version TEXT $.msg AS msg TEXT
```
And I had executed the following query to retrieve information about log_json_v1:32

```
FT.SEARCH my_index "*" RETURN 2 version msg
```
Following results was retrieved 
```
1) "1"
2) "log_json_v1:32"
3) 1) "version"
   2) "32"
   3) "msg"
   4) "Random message"
```
Note: I have changed the msg field value for example purpose.

Also, try to give different field name for time, as it may collide with predefined variable name `time`.

**Comment by musiye14** [comment]
It's strange, I followed your command and it's still nil, I suspect it's a version problem.

**Comment by shrihari-nasdaq** [comment]
What version of RediSearch are you using currently?

**Comment by musiye14** [comment]
RediSearch's version of how to view ？ the latest container of docker I was fetching at the time

**Comment by musiye14** [comment]
```
10.11.185.73:6001> module list
1) 1) "name"
   2) "bf"
   3) "ver"
   4) (integer) 20802
   5) "path"
   6) "/opt/redis-stack/lib/redisbloom.so"
   7) "args"
   8) (empty array)
2) 1) "name"
   2) "search"
   3) "ver"
   4) (integer) 21005
   5) "path"
   6) "/opt/redis-stack/lib/redisearch.so"
   7) "args"
   8) 1) "MAXSEARCHRESULTS"
      2) "10000"
      3) "MAXAGGREGATERESULTS"
      4) "10000"
3) 1) "name"
   2) "timeseries"
   3) "ver"
   4) (integer) 11202
   5) "path"
   6) "/opt/redis-stack/lib/redistimeseries.so"
   7) "args"
   8) (empty array)
4) 1) "name"
   2) "RedisCompat"
   3) "ver"
   4) (integer) 1
   5) "path"
   6) "/opt/redis-stack/lib/rediscompat.so"
   7) "args"
   8) (empty array)
5) 1) "name"
   2) "ReJSON"
   3) "ver"
   4) (integer) 20803
   5) "path"
   6) "/opt/redis-stack/lib/rejson.so"
   7) "args"
   8) (empty array)
6) 1) "name"
   2) "redisgears_2"
   3) "ver"
   4) (integer) 20020
   5) "path"
   6) "/opt/redis-stack/lib/redisgears.so"
   7) "args"
   8) 1) "v8-plugin-path"
      2) "/opt/redis-stack/lib/libredisgears_v8_plugin.so"
```

**Comment by musiye14** [comment]
What's your version? I'll try importing this one.

**Comment by musiye14** [comment]
hi @shrihari-nasdaq 
What's your version

**Comment by meiravgri** [comment]
Hi @musiye14,
could you please run the same query with `TIMEOUT 0`?

**Comment by musiye14** [comment]
@meiravgri 
```
root@c4dbcffc6b4a:/# redis-cli -c -p 10.11.185.73 -p 6001 -a test123 FT.SEARCH jsonIndex '*' TIMEOUT 0
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
 1) (integer) 26407
 2) "log_json:SO3GameServer:20240729-004842"
 3) (nil)
 4) "log_json:SO3GameServer:20240727-040510"
 5) (nil)
 6) "log_json:SO3GameCenter:20240805-191555"
 7) (nil)
 8) "log_json:SO3GameServer:20240727-141141"
 9) (nil)
10) "log_json:SO3GameCenter:20240807-181616"
11) (nil)
12) "log_json:SO3GameServer:20240727-150100"
13) (nil)
14) "log_json:SO3GameServer:20240727-051551"
15) (nil)
16) "log_json:SO3GameCenter:20240807-113112"
17) (nil)
18) "log_json:SO3GameServer:20240726-235820"
19) (nil)
20) "log_json:SO3GameServer:20240727-054223"
21) (nil)
```

**Comment by meiravgri** [comment]
This is indeed unexpected.
Could you please share your `FT.CREATE` command and any additional information that might assist in reproducing this behavior?

**Comment by musiye14** [comment]
The data I created using python
```
def create_index():
    # Define the schema for JSON fields using JSON paths (e.g., $.version, $.time)
    schema = (
        redisearch.TagField("$.version", as_name="version"),
        redisearch.TextField("$.time", as_name="time"),            # Text field for time
        redisearch.TagField("$.actions", as_name="actions"),       # Tag field for actions
        redisearch.TextField("$.filelist", as_name="filelist"),    # Text field for filelist
        redisearch.TextField("$.msg", as_name="msg")               # Text field for msg
    )

    # Create the RedisSearch client
    client = Client('my_index', conn=redis_client)  # Ensure index name matches 'item1'

    # Drop the index if it exists
    try:
        client.drop_index()
    except:
        pass  # Ignore if index doesn't exist

    # Create the index with the schema and prefix for JSON data
    definition = IndexDefinition(prefix=['log_json_v1:'], language='chinese',index_type=IndexType.JSON)

    # Create the index
    res = client.create_index(fields=schema, definition=definition)
    # client.load_document(1)
    print(f"Index created: {res}")
    print(client.search("*"))
```

```
def process_file(file_path):
    with open(file_path, 'r', encoding='gbk') as file:
        filename = os.path.basename(file_path).split('_')[0]

        pipe = redis_client.pipeline(transaction=False)
        count = 0
        for line in file:
            match = log_pattern.match(line.strip())
            if match:
                timestamp, level, content = match.groups()
                log_entry = {
                    "timestamp": timestamp,
                    "level": level,
                    "content": content
                }
                redis_key = f"log:{filename}:{timestamp}"

                pipe.hset(redis_key, mapping=log_entry) 
                count += 1

                if count % 10000 == 0:
                    pipe.execute()

        pipe.execute()
```

```
xml 
<logentry
   revision="3">
<author>123</author>
<date>2024-01-19T02:59:28.140495Z</date>
<paths>
<path
   kind="file"
   action="M"
   prop-mods="false"
   text-mods="true">/trunk/Old/Jx3mHelperTray/Commands/Global/GlobalCommands.cs</path>
</paths>
<msg>123</msg>
```

**Comment by musiye14** [comment]
@meiravgri  I created the index of the hash using
```
127.0.0.1:6001> FT.CREATE hindex ON HASH PREFIX 1 log: LANGUAGE "chinese" SCHEMA content TEXT
OK
```
127.0.0.1:6001> FT.SEARCH hindex *
 1) (integer) 222983
 2) "log:SO3GameCenter:20240801-124115"
 3) (nil)
 4) "log:SO3GameCenter:20240727-123340"
 5) (nil)
 ```
 data is
 ```
key:  
   log:gc:20240823-161517

data : 
  timestamp:"20240729-022853"
  level:"ERROR"
  content:"ServerLoad"

 ```

**Comment by meiravgri** [comment]
Hi @musiye14,
I noticed that in [this comment](https://github.com/RediSearch/RediSearch/issues/5034#issuecomment-2367530170) you created a json index, but used hset to add keys to the database. It seems like this might not be the complete script you used.
Additionally, I observed that your data contains Chinese characters and a special encoding format, which could potentially cause parsing issues.

Could you please share the full script and detailed steps to reproduce the issue, including any sample data? Specifically, data that includes special characters, such as Chinese words, would help us better investigate the problem.
Thanks!

**Comment by musiye14** [comment]
How do I know what version of redisearch I'm using I didn't compile it myself I installed it directly through the container inside docker I think it might be the version I'd like to replace the version to see if that's the problem I'm using win10 docker

**Comment by meiravgri** [comment]
@musiye14 Thanks for the detailed script.
I'll open a ticket and my team and i will keep you update 
you can see the module version in module list
2) 1) "name"
   2) "search"
   3) "ver"
   **4) (integer) 21005**
   5) "path"
   6) "/opt/redis-stack/lib/redisearch.so"
   7) "args"
   8) 1) "MAXSEARCHRESULTS"
      2) "10000"
      3) "MAXAGGREGATERESULTS"
      4) "10000"

you are using 2.10.5 :)

**Comment by musiye14** [comment]
@meiravgri I found that after setting the cluster-enabled no and making a separate node, it is possible to query it. Is there any configuration that affects index searching json data in clustered mode?

**Comment by musiye14** [comment]
Changing the version solved the problem
Now using redis/redis-stack-server:6.2.6-v13-x86_64

**Comment by musiye14** [comment]
A new problem is that my index can find all the data in non-clustered but not in clustered Is there any parameter that needs to be set to support clustered redisearch?

**Comment by meiravgri** [comment]
Glad to hear that the first issue was already solved.

Could you clarify the issue you are currently encountering?

**Comment by musiye14** [comment]
ok
``
 datas = [{"version":1, "filelist": "a.txt"},{"version":2, "filelist": "b.txt"},{"version":3, "filelist": "c.txt"},{"version":2, "filelist". "a.txt"}]
``
I realized that the index I created could only find the data on one node and not all of it For example, for the above data executing the command: FT.SEARCH index2 * TIMEOUT 0  would yield the following result
```
1) "2"
2) "log_json_v1:2"
3) 1) "$"
   2) "{\"version\":2,\"filelist\":\"b.txt\",\"key\":\"log_json_v1:2\"}"
4) "log_json_v1:3"
5) 1) "$"
   2) "{\"version\":3,\"filelist\":\"c.txt\",\"key\":\"log_json_v1:3\"}"
```
![image](https://github.com/user-attachments/assets/982fad80-7fdd-48ea-98fd-caca72d13894)
![image](https://github.com/user-attachments/assets/835881b8-e537-45c2-bbb8-5060d17b6b26)

**Comment by musiye14** [comment]
@meiravgri I checked and it looks like you need RSCoordinator for this to be compatible with cluster queries? But I have read that redisearch has integrated this feature in some version.
https://forum.redis.io/t/anything-to-do-to-get-redisearch-to-search-across-clusters/1943/10 “The redis-stack-server distribution (docker or binary) is not including rscoodinator.” Is it true?

**Comment by meiravgri** [comment]
@musiye14 
This is correct. 
You can check [8.0-M01](https://hub.docker.com/_/redis), Redis image shipped with all modules, in which search module includes the coordinator. (redis-stack is not needed anymore)
Let me know if it worked for you

**Comment by musiye14** [comment]
hi @meiravgri I used [8.0-M01](https://hub.docker.com/_/redis/tags) and solved all my problems. Thank you very much for your help

**Comment by meiravgri** [comment]
I'm glad to hear!
I'm closing the ticket for now.
Please feel free to reach out if you have further questions.
